### PR TITLE
LPD-42546 Create a sample for a FDS View component

### PR DESCRIPTION
**Pull request by markocikos**
### References

- Parent Story: [LPD-42544 Create a sample for a FDS View component so that it can be tested](https://issues.liferay.com/browse/LPD-42544)
- Followup on https://github.com/liferay-frontend/liferay-portal/pull/4572

### What is the goal of this PR?

Main change from previous version is navigation now uses `clay:navigation-bar`. I updated tests and polished them a bit.

I'm opening this as a normal PR, but is still needs work on the carousel implementation, see https://github.com/liferay-frontend/liferay-portal/pull/4572#pullrequestreview-2450558358. @chestofwonders Please rebase your new work on top of this PR. There might be some details for me to change, but mostly I believe my part on this is done.

### What does it look like?

https://github.com/user-attachments/assets/bb9474ec-88c6-4835-8a0d-5780d0af8a75

image

### CODE REVIEW

File: modules/apps/frontend-data-set/frontend-data-set-web/src/main/resources/META-INF/resources/FrontendDataSetContext.tsx [hunk 1]
```diff
@@ -14,7 +14,10 @@ export interface IFrontendDataSetContext {
 	applyItemInlineUpdates: Function;
 	createInlineItem: Function;
 	customDataRenderers?: Array<any>;
-	customRenderers?: {tableCell?: Array<TRenderer>};
+	customRenderers?: {
+		tableCell?: Array<TRenderer>;
+		views?: Array<TRenderer>;
+	};
```
Comment (markocikos) [inline modules/apps/frontend-data-set/frontend-data-set-web/src/main/resources/META-INF/resources/FrontendDataSetContext.tsx:20]: Updates types, based on https://github.com/liferay-frontend/liferay-portal/pull/4571#discussion_r1850709870

I also changed `view` to `views`. It's not consistent with `tableCell`, but it pained me too much to have an array called with singular :sweat_smile:

File: modules/test/playwright/tests/frontend-data-set-web/clayTable.spec.ts
Comment (markocikos) [inline modules/test/playwright/tests/frontend-data-set-web/clayTable.spec.ts:1]: I merged all tests on "Customized" sample into one file, but left out this one. It complicates things, as it changes markup by switching on FF. We can do this in a separate task.

File: modules/test/playwright/tests/frontend-data-set-web/customized.spec.ts [hunk 2]
```diff
@@ -0,0 +1,534 @@
...
+			.locator('.filters-dropdown')
+			.getByText('Filter');
+
+		await expect(filterButton).toBeInViewport();
+
+		await clickAndExpectToBeVisible({
+			autoClick: true,
+			target: clientExtensionMenuItem,
+			trigger: filterButton,
+		});
```
Comment (markocikos) [inline modules/test/playwright/tests/frontend-data-set-web/customized.spec.ts:512]: There was a flaky test here, caused by [missing `await`s on clicks](https://github.com/liferay/liferay-portal/blob/master/modules/test/playwright/tests/frontend-data-set-web/clientExtensionFilter.spec.ts#L69-L84). @kresimir-coko It looks you tried to patch it with `timeout: 500`, but that was not the root cause. In any case, I removed the separate availability check in refactor, as it is not needed. We are checking availability as a part of behavior check.

**Comment by markocikos** [comment]
@chestofwonders I saw you created a separate subtask for carousel component, so I cut the draft commit from this PR. If all is good with you and @dsanz , we can push my part as it is, with the implementation placeholder.

**Comment by markocikos** [comment]
ci:test:sf

**Comment by markocikos** [comment]
ci:test:relevant

**Comment by markocikos** [comment]
ci:test:relevant

**Comment by dsanz** [comment]
let's check if @chestofwonders can add on top of this today, thus sending a single PR

**Comment by chestofwonders** [comment]
> let's check if @chestofwonders can add on top of this today, thus sending a single PR

I've added my changes :+1:

**Comment by markocikos** [comment]
ci:forward

**Comment by markocikos** [comment]
@chestofwonders the failure in https://github.com/liferay-frontend/liferay-portal/pull/4576#issuecomment-2493683788 is related

**Comment by markocikos** [comment]
ci:stop

**Comment by markocikos** [comment]
@chestofwonders Besides missing TS export, there is also a TS error
```js
src/main/resources/META-INF/resources/js/CarouselView.tsx(107,27): error TS2739: Type 'ICarouselSchema' is missing the following properties from type 'ICardSchema': description, link, sticker, symbol
```

**Comment by chestofwonders** [comment]
ci:test:sf

**Comment by dsanz** [comment]
@chestofwonders can we check this schema in the sample with the existing carousel component? I believe we'll need to djust the schema we provide in the sample to make it work

**Review by markocikos — COMMENTED** [review]
@chestofwonders just one nit on naming inline

File: modules/apps/frontend-data-set/frontend-data-set-sample-web/src/main/resources/META-INF/resources/js/CarouselView.tsx [hunk 3]
```diff
@@ -3,14 +3,110 @@
...
+		setSelectedIndex(newIndex);
+	};
+
+	const handleNextClick = () => {
+		const newIndex =
+			selectedIndex === items.length - 1 ? 0 : selectedIndex + 1;
+		setSelectedIndex(newIndex);
+	};
+
+	const {name, size, url} = items[selectedIndex];
```
[the remark this answers is not in the document]
Comment (markocikos) [reply modules/apps/frontend-data-set/frontend-data-set-sample-web/src/main/resources/META-INF/resources/js/CarouselView.tsx]: Just note that schema only provides mapping to data. URL must be in the data, and in [data this sample is using](https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-data-set/frontend-data-set-sample-web/src/main/java/com/liferay/frontend/data/set/sample/web/internal/portlet/FDSSamplePortlet.java#L107-L135) we currently don't have an image url field.

Not related to task, but @dsanz , at some point we should move this sample data definition and generation to batch engine :slightly_smiling_face:

[the remark this answers is not in the document]
Comment (markocikos) [reply modules/apps/frontend-data-set/frontend-data-set-sample-web/src/main/resources/META-INF/resources/js/CarouselView.tsx]: As far as I'm concerned, we can push this without the image, I'd just remove the broken bit from UI

image

If we do want the image, it needs to be added to object definition and generation, as well as mapped in schema.

[the remark this answers is not in the document]
Comment (chestofwonders) [reply modules/apps/frontend-data-set/frontend-data-set-sample-web/src/main/resources/META-INF/resources/js/CarouselView.tsx]: > @chestofwonders now we have an schema, so we can get the data from the item using the props values indicated in the schema.
> 
> As for the image we'll need to add a new string field to the FDSSample object definition, which can be mapped in the schema.
> 
> Values for that field can just be the same image URL, such as `/image/company_logo` which is going to work though introduces an external dependency. I'm not worried because sample is meant to illustrate, we don't need to test this component thoroughly

@dsanz getting props values through schema were added [here](https://github.com/liferay-frontend/liferay-portal/pull/4576/commits/f473655feaa12343d3a854eb8204eec0ddc68299#diff-e2e4181e72a81b485b48ea55d2b37da52b400d6f277df555251d815c7debd78b). Did you miss something else related to that?

[the remark this answers is not in the document]
Comment (dsanz) [reply modules/apps/frontend-data-set/frontend-data-set-sample-web/src/main/resources/META-INF/resources/js/CarouselView.tsx]: Oh great then! I must have checked an older commit, sorry about re-asking.

> Not related to task, but @dsanz , at some point we should move this sample data definition and generation to batch engine 🙂

yes, that's pending. Perhaps we can wait till some test involving the sample fails

And finally, yep, image shall be in the data and populated. I suggested using a fixed value for it. This is what I had in mind:
image
(plus the mapping)

So, basically we can push like it is (because it's enough), or just add the image as follows (because it's cheap). 

I think this is opt-in so I'll let @chestofwonders decide to add or jsut forward as it is

[the remark this answers is not in the document]
Comment (chestofwonders) [reply modules/apps/frontend-data-set/frontend-data-set-sample-web/src/main/resources/META-INF/resources/js/CarouselView.tsx]: @dsanz I think it's a good improvement, I'm rather in favor of adding it

File: modules/apps/frontend-data-set/frontend-data-set-sample-web/src/main/java/com/liferay/frontend/data/set/sample/web/internal/portlet/FDSSamplePortlet.java [hunk 4]
```diff
@@ -129,6 +129,10 @@ private synchronized void _generate(long companyId) throws Exception {
 						ObjectFieldConstants.BUSINESS_TYPE_TEXT,
 						ObjectFieldConstants.DB_TYPE_STRING, true, false, null,
 						"Color", "color", false),
+					ObjectFieldUtil.createObjectField(
```
Comment (chestofwonders) [inline modules/apps/frontend-data-set/frontend-data-set-sample-web/src/main/java/com/liferay/frontend/data/set/sample/web/internal/portlet/FDSSamplePortlet.java:132]: I've added `imageURL` in object definition, so we can map it later to `/image/company_logo`

**Comment by markocikos** [comment]
ci:forward

**Comment by markocikos** [comment]
@chestofwonders please install Prettier, to avoid [this kind of nonsense](https://github.com/liferay-frontend/liferay-portal/pull/4576#issuecomment-2513744424).

**Comment by markocikos** [comment]
ci:forward

**Comment by chestofwonders** [comment]
I've added 

> @chestofwonders please install Prettier, to avoid [this kind of nonsense](https://github.com/liferay-frontend/liferay-portal/pull/4576#issuecomment-2513744424).

I've just configure it :fearful:

**Comment by markocikos** [comment]
ci:forward

**Comment by markocikos** [comment]
ci:forward

**Comment by markocikos** [comment]
ci:forward

**Comment by dsanz** [comment]
ci:test:relevant

**Comment by dsanz** [comment]
ci:reevaluate:1357401_6388

**Comment by markocikos** [comment]
ci:forward

**Comment by markocikos** [comment]
ci:forward

**Comment by markocikos** [comment]
ci:forward
